//
//  SimVsRigHTMLGenerator.swift
//  Josh Well Control for Mac
//
//  Standalone HTML comparison chart: sim lines + rig per-stand scatter with error bars.
//  Follows TorqueDragHTMLGenerator pattern with Chart.js 4.4.0 CDN.
//

import Foundation
import UniformTypeIdentifiers

#if os(macOS)
import AppKit
#endif

struct SimVsRigHTMLData {
    let wellName: String
    let importName: String
    let tripType: String
    let generatedDate: Date
    // Sim data (arrays of same length, sorted by MD)
    let simMD: [Double]
    let simPickup_kDaN: [Double]
    let simSlackOff_kDaN: [Double]
    let simFreeHanging_kDaN: [Double]
    // Rig per-stand data
    let stands: [RigStandData]
    // Static weights (trip-in only)
    let staticWeights: [RigStaticWeight]
    // Zone boundaries (MD where zone changes)
    let zoneBoundaries: [(md: Double, zone: String)]
    // Statistics
    let comparison: ComparisonResult
}

class SimVsRigHTMLGenerator {
    static let shared = SimVsRigHTMLGenerator()
    private init() {}

    func generateHTML(for data: SimVsRigHTMLData) -> String {
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "d MMM yyyy, HH:mm"
        let dateStr = dateFormatter.string(from: data.generatedDate)

        let tripLabel = data.tripType == "in" ? "Trip In" : "Trip Out"
        let primaryLabel = data.tripType == "in" ? "Slack-off (Sim)" : "Pickup (Sim)"

        return """
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Sim vs Rig - \(escapeHTML(data.wellName)) - \(tripLabel)</title>
            <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
            <style>\(generateCSS())</style>
        </head>
        <body>
            <header>
                <div class="header-content">
                    <h1>Sim vs Rig Comparison &mdash; \(tripLabel)</h1>
                    <span class="well-name">\(escapeHTML(data.wellName)) &bull; \(escapeHTML(data.importName))</span>
                </div>
            </header>
            <main>
                <section class="card">
                    <h2>Hook Load vs Depth</h2>
                    <div class="chart-wrapper">
                        <canvas id="compChart"></canvas>
                    </div>
                </section>

                <section class="card">
                    <h2>Residual Statistics (Rig \u{2212} Sim) &mdash; \(primaryLabel)</h2>
                    \(generateStatsTable(data.comparison))
                </section>
            </main>
            <footer>
                <p>Generated by Josh Well Control &mdash; \(dateStr)</p>
            </footer>
            <script>
            \(generateChartData(data))
            \(generateJavaScript(data))
            </script>
        </body>
        </html>
        """
    }

    #if os(macOS)
    func exportHTML(_ html: String, defaultName: String) {
        let savePanel = NSSavePanel()
        savePanel.allowedContentTypes = [.html]
        savePanel.nameFieldStringValue = defaultName
        savePanel.title = "Export Sim vs Rig Chart"

        if savePanel.runModal() == .OK, let url = savePanel.url {
            try? html.write(to: url, atomically: true, encoding: .utf8)
        }
    }
    #endif

    // MARK: - CSS

    private func generateCSS() -> String {
        """
        :root {
            --brand-color: #52a5bf;
            --bg-color: #f5f5f5;
            --card-bg: #ffffff;
            --text-color: #333333;
            --text-light: #666666;
            --border-color: #e0e0e0;
        }
        @media (prefers-color-scheme: dark) {
            :root {
                --bg-color: #1a1a1a;
                --card-bg: #2a2a2a;
                --text-color: #e0e0e0;
                --text-light: #999999;
                --border-color: #444444;
            }
            tr:nth-child(even) { background: #333 !important; }
            th:hover { background: #4795ab; }
        }
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background: var(--bg-color);
            color: var(--text-color);
            line-height: 1.5;
        }
        header {
            background: var(--brand-color);
            color: white;
            padding: 16px 24px;
            position: sticky; top: 0; z-index: 100;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }
        .header-content {
            max-width: 1200px; margin: 0 auto;
            display: flex; justify-content: space-between; align-items: center;
        }
        header h1 { font-size: 1.5rem; font-weight: 600; }
        .well-name { opacity: 0.9; font-size: 0.9rem; }
        main { max-width: 1200px; margin: 0 auto; padding: 24px; }
        .card {
            background: var(--card-bg);
            border-radius: 8px; padding: 20px; margin-bottom: 20px;
            box-shadow: 0 1px 3px rgba(0,0,0,0.1);
        }
        .card h2 {
            color: var(--brand-color); font-size: 1.1rem;
            margin-bottom: 16px; padding-bottom: 8px;
            border-bottom: 1px solid var(--border-color);
        }
        .chart-wrapper { position: relative; height: 500px; padding: 12px; }
        .chart-wrapper canvas { width: 100% !important; height: 100% !important; }
        table { width: 100%; border-collapse: collapse; font-size: 0.85rem; }
        th {
            background: var(--brand-color); color: white;
            padding: 10px 8px; text-align: right; white-space: nowrap;
        }
        th:first-child { text-align: left; }
        td { padding: 8px; text-align: right; border-bottom: 1px solid var(--border-color); }
        td:first-child { text-align: left; font-weight: 500; }
        tr:nth-child(even) { background: var(--bg-color); }
        .total-row { background: #e0e0e0 !important; font-weight: 600; }
        footer { text-align: center; padding: 20px; color: var(--text-light); font-size: 0.8rem; }
        """
    }

    // MARK: - Chart Data

    private func generateChartData(_ data: SimVsRigHTMLData) -> String {
        let simPickupJSON = zip(data.simMD, data.simPickup_kDaN).map { "{x:\(f1($0)),y:\(f1($1))}" }.joined(separator: ",")
        let simSlackJSON = zip(data.simMD, data.simSlackOff_kDaN).map { "{x:\(f1($0)),y:\(f1($1))}" }.joined(separator: ",")
        let simFreeJSON = zip(data.simMD, data.simFreeHanging_kDaN).map { "{x:\(f1($0)),y:\(f1($1))}" }.joined(separator: ",")

        let rigAvgJSON = data.stands.map { "{x:\(f1($0.standMidMD_m)),y:\(f1($0.avgHL_kDaN))}" }.joined(separator: ",")
        let rigMinJSON = data.stands.map { "{x:\(f1($0.standMidMD_m)),y:\(f1($0.minHL_kDaN))}" }.joined(separator: ",")
        let rigMaxJSON = data.stands.map { "{x:\(f1($0.standMidMD_m)),y:\(f1($0.maxHL_kDaN))}" }.joined(separator: ",")

        var staticJSON = "[]"
        if !data.staticWeights.isEmpty {
            staticJSON = "[" + data.staticWeights.map { "{x:\(f1($0.depth_m)),y:\(f1($0.hookLoad_kDaN))}" }.joined(separator: ",") + "]"
        }

        return """
        const simPickup = [\(simPickupJSON)];
        const simSlack = [\(simSlackJSON)];
        const simFree = [\(simFreeJSON)];
        const rigAvg = [\(rigAvgJSON)];
        const rigMin = [\(rigMinJSON)];
        const rigMax = [\(rigMaxJSON)];
        const staticWeights = \(staticJSON);
        const tripType = "\(data.tripType)";
        """
    }

    // MARK: - JavaScript

    private func generateJavaScript(_ data: SimVsRigHTMLData) -> String {
        """
        document.addEventListener('DOMContentLoaded', function() {
            const ctx = document.getElementById('compChart');
            if (!ctx) return;

            const datasets = [
                {
                    label: 'Pickup (Sim)',
                    data: simPickup,
                    borderColor: '#4caf50',
                    showLine: true, pointRadius: 0, borderWidth: 2
                },
                {
                    label: 'Slack-off (Sim)',
                    data: simSlack,
                    borderColor: '#f44336',
                    showLine: true, pointRadius: 0, borderWidth: 2
                },
                {
                    label: 'Free Hanging (Sim)',
                    data: simFree,
                    borderColor: '#999999',
                    borderDash: [5, 3],
                    showLine: true, pointRadius: 0, borderWidth: 1.5
                },
                {
                    label: 'Rig Avg',
                    data: rigAvg,
                    borderColor: '#ff9800',
                    backgroundColor: 'rgba(255, 152, 0, 0.7)',
                    showLine: false, pointRadius: 3, borderWidth: 1,
                    pointStyle: 'circle'
                },
                {
                    label: 'Rig Min',
                    data: rigMin,
                    borderColor: 'rgba(255, 152, 0, 0.3)',
                    showLine: true, pointRadius: 0, borderWidth: 1,
                    borderDash: [2, 2], fill: false
                },
                {
                    label: 'Rig Max',
                    data: rigMax,
                    borderColor: 'rgba(255, 152, 0, 0.3)',
                    showLine: true, pointRadius: 0, borderWidth: 1,
                    borderDash: [2, 2], fill: '-1'
                }
            ];

            if (staticWeights.length > 0) {
                datasets.push({
                    label: 'Static Weight (Rig)',
                    data: staticWeights,
                    borderColor: '#00bcd4',
                    backgroundColor: 'rgba(0, 188, 212, 0.5)',
                    showLine: true, pointRadius: 2, borderWidth: 1.5,
                    pointStyle: 'triangle'
                });
            }

            new Chart(ctx, {
                type: 'scatter',
                data: { datasets: datasets },
                options: {
                    responsive: true,
                    maintainAspectRatio: false,
                    scales: {
                        x: {
                            title: { display: true, text: 'Measured Depth (m)' },
                            grid: { color: 'rgba(128,128,128,0.2)' }
                        },
                        y: {
                            title: { display: true, text: 'Hook Load (kDaN)' },
                            grid: { color: 'rgba(128,128,128,0.2)' }
                        }
                    },
                    plugins: {
                        tooltip: {
                            callbacks: {
                                label: function(context) {
                                    return context.dataset.label + ': ' + context.parsed.y.toFixed(1) + ' kDaN at ' + context.parsed.x.toFixed(0) + ' m';
                                }
                            }
                        }
                    }
                }
            });
        });
        """
    }

    // MARK: - Statistics Table

    private func generateStatsTable(_ comparison: ComparisonResult) -> String {
        var html = """
        <table>
            <thead>
                <tr>
                    <th>Zone</th>
                    <th>Stands</th>
                    <th>Mean (kDaN)</th>
                    <th>P10</th>
                    <th>P50</th>
                    <th>P90</th>
                    <th>Std Dev</th>
                </tr>
            </thead>
            <tbody>
        """

        for stat in comparison.zoneStats {
            html += """
                <tr>
                    <td>\(escapeHTML(stat.zone))</td>
                    <td>\(stat.count)</td>
                    <td>\(f1(stat.meanResidual))</td>
                    <td>\(f1(stat.p10))</td>
                    <td>\(f1(stat.p50))</td>
                    <td>\(f1(stat.p90))</td>
                    <td>\(f1(stat.stddev))</td>
                </tr>
            """
        }

        let o = comparison.overallStats
        html += """
                <tr class="total-row">
                    <td>\(escapeHTML(o.zone))</td>
                    <td>\(o.count)</td>
                    <td>\(f1(o.meanResidual))</td>
                    <td>\(f1(o.p10))</td>
                    <td>\(f1(o.p50))</td>
                    <td>\(f1(o.p90))</td>
                    <td>\(f1(o.stddev))</td>
                </tr>
            </tbody>
        </table>
        """
        return html
    }

    // MARK: - Helpers

    private func escapeHTML(_ str: String) -> String {
        str.replacingOccurrences(of: "&", with: "&amp;")
           .replacingOccurrences(of: "<", with: "&lt;")
           .replacingOccurrences(of: ">", with: "&gt;")
           .replacingOccurrences(of: "\"", with: "&quot;")
    }

    private func f0(_ v: Double) -> String { String(format: "%.0f", v) }
    private func f1(_ v: Double) -> String { String(format: "%.1f", v) }
}
